import os
from os.path import join, dirname, abspath

IMAGES = config['imgs'] # image list specified through the parameters.yaml config file
LOGDIR = 'log-test' # directory with logs

print(workflow.basedir) # the directory where the Snakefile is located

bin_dir = join(dirname(workflow.basedir), 'bin') # directory with executables
print(bin_dir)


def check_make(directory):
    os.makedirs(directory, exist_ok=True)


# the `main` rule requires the label layer to be created
# this invokes the execution of the thresholding rule which runs the fractal module
rule main:
    input:
        expand('{sample}/labels/{labname}', sample=IMAGES, labname=config['label_name'])

# the `threshold` rule accepts a zarr image and adds a new layer with the thresholded channels
rule threshold:
    input:
        zarr_img = '{sample}'
    output:
        label_image = directory(expand('{{sample}}/labels/{labname}', labname=config['label_name']))
    conda:
        'snakemake-threshold'
    params:
        label_name = config['label_name'],
        threshold = config['threshold'],
        min_size = config['min_size'],
        overwrite = config['overwrite']
    shell:
        """
        python {bin_dir}/thresholding_label_task.py thresholding_label_task \
        --zarr_url {input.zarr_img} \
        --threshold {params.threshold} \
        --channel '{{"label": "DAPI"}}' \
        --min_size {params.min_size} \
        --overwrite {params.overwrite} \
        --label_name {params.label_name}
        """

