import os
from os.path import join


IMAGES = ['/home/sysbio/snakemake-thresholding/data/ngff_example/my_image']
LOGDIR = 'log-test'


def check_make(directory):
    os.makedirs(directory, exist_ok=True)

rule main:
    input:
        expand('{sample}/labels/{labname}', sample=IMAGES, labname=config['label_name'])


rule threshold:
    input:
        zarr_img = '{sample}'
    output:
        label_image = directory(expand('{{sample}}/labels/{labname}', labname=config['label_name']))
    conda:
        'snakemake-threshold'
    params:
        label_name = config['label_name'],
        threshold = config['threshold'],
        min_size = config['min_size'],
        overwrite = config['overwrite']
    shell:
        """
        python ../bin/thresholding_label_task.py thresholding_label_task \
        --zarr_url {input.zarr_img} \
        --threshold {params.threshold} \
        --channel '{{"label": "DAPI"}}' \
        --min_size {params.min_size} \
        --overwrite {params.overwrite} \
        --label_name {params.label_name}
        """

